### ISSUE TITLE
Material appears pink when run in Unity Editor

### ISSUE THREAD

**Issue by afjk** [from2001/VRM_VisualScriptingNodes#25]
<img width="769" alt="image" src="https://github.com/from2001/VRM_VisualScriptingNodes/assets/4654522/e7275b2b-831b-4b0e-8fc4-f013e4735af1">

If you want to run only on the built VisionOS, you can specify the following.
```
 #if !UNITY_EDITOR && UNITY_VISIONOS
// Only executed on built VisionOS
 #endif
```

**Comment by from2001** [comment]
It happens only with Unity editor with VisionOs build settings now.

**Comment by from2001** [comment]
I fixed the function to check whether app is running on VisionOS 

```cs
        /// <summary>
        /// Return true if current OS is VisionOS.
        /// </summary>
        /// <returns></returns>
        public static bool IsVisionOS()
        {
            //When operatingSystem is "visionOS", return true
            if (SystemInfo.operatingSystem.Contains("visionOS")) return true;
            if (Application.platform == RuntimePlatform.VisionOS) return true;
#if UNITY_VISIONOS
            return true;
#else
            return false;
#endif
        }
```

**Comment by from2001** [comment]
https://github.com/from2001/VRM_VisualScriptingNodes/pull/26/commits/765a87627720d126ba060e5e9894062ba1aa4f7d
